export default [{name: "Greece", id: "olympics_GRE"},
    {name: "Afghanistan", id: "olympics_AFG"},
    {name: "South Africa", id: "olympics_RSA"},
    {name: "Albania", id: "olympics_ALB"},
    {name: "Germany", id: "olympics_GER"},
    {name: "Andorra", id: "olympics_AND"},
    {name: "Angola", id: "olympics_ANG"},
    {name: "Former Yugoslav Republic of Macedonia", id: "olympics_MKD"},
    {name: "Antigua and Barbuda", id: "olympics_ANT"},
    {name: "Saudi Arabia", id: "olympics_KSA"},
    {name: "Algeria", id: "olympics_ALG"},
    {name: "Argentina", id: "olympics_ARG"},
    {name: "Armenia", id: "olympics_ARM"},
    {name: "Aruba", id: "olympics_ARU"},
    {name: "Australia", id: "olympics_AUS"},
    {name: "Austria", id: "olympics_AUT"},
    {name: "Azerbaijan", id: "olympics_AZE"},
    {name: "Bahamas", id: "olympics_BAH"},
    {name: "Bahrain", id: "olympics_BRN"},
    {name: "Bangladesh", id: "olympics_BAN"},
    {name: "Barbados", id: "olympics_BAR"},
    {name: "Belarus", id: "olympics_BLR"},
    {name: "Belgium", id: "olympics_BEL"},
    {name: "Belize", id: "olympics_BIZ"},
    {name: "Benin", id: "olympics_BEN"},
    {name: "Bermuda", id: "olympics_BER"},
    {name: "Bolivia", id: "olympics_BOL"},
    {name: "Bosnia and Herzegovina", id: "olympics_BIH"},
    {name: "Botswana", id: "olympics_BOT"},
    {name: "Brunei Darussalam", id: "olympics_BRU"},
    {name: "Bulgaria", id: "olympics_BUL"},
    {name: "Burkina Faso", id: "olympics_BUR"},
    {name: "Burundi", id: "olympics_BDI"},
    {name: "Bhutan", id: "olympics_BHU"},
    {name: "Cape Verde", id: "olympics_CPV"},
    {name: "Cameroon", id: "olympics_CMR"},
    {name: "Cambodia", id: "olympics_CAM"},
    {name: "Canada", id: "olympics_CAN"},
    {name: "Qatar", id: "olympics_QAT"},
    {name: "Kazakhstan", id: "olympics_KAZ"},
    {name: "Chad", id: "olympics_CHA"},
    {name: "Chile", id: "olympics_CHI"},
    {name: "Cyprus", id: "olympics_CYP"},
    {name: "Singapore", id: "olympics_SIN"},
    {name: "Colombia", id: "olympics_COL"},
    {name: "Comoros", id: "olympics_COM"},
    {name: "Congo", id: "olympics_CGO"},
    {name: "Ivory Coast", id: "olympics_CIV"},
    {name: "Costa Rica", id: "olympics_CRC"},
    {name: "Croatia", id: "olympics_CRO"},
    {name: "Cuba", id: "olympics_CUB"},
    {name: "Denmark", id: "olympics_DEN"},
    {name: "Djibouti", id: "olympics_DJI"},
    {name: "Dominica", id: "olympics_DMA"},
    {name: "Egypt", id: "olympics_EGY"},
    {name: "El Salvador", id: "olympics_ESA"},
    {name: "United Arab Emirates", id: "olympics_UAE"},
    {name: "Ecuador", id: "olympics_ECU"},
    {name: "Eritrea", id: "olympics_ERI"},
    {name: "Slovakia", id: "olympics_SVK"},
    {name: "Slovenia", id: "olympics_SLO"},
    {name: "Spain", id: "olympics_ESP"},
    {name: "Federated States of Micronesia", id: "olympics_FSM"},
    {name: "United States of America", id: "olympics_USA"},
    {name: "Estonia", id: "olympics_EST"},
    {name: "Ethiopia", id: "olympics_ETH"},
    {name: "Russian Federation", id: "olympics_RUS"},
    {name: "Fiji", id: "olympics_FIJ"},
    {name: "Philippines", id: "olympics_PHI"},
    {name: "Finland", id: "olympics_FIN"},
    {name: "France", id: "olympics_FRA"},
    {name: "Gabon", id: "olympics_GAB"},
    {name: "Gambia", id: "olympics_GAM"},
    {name: "Ghana", id: "olympics_GHA"},
    {name: "Georgia", id: "olympics_GEO"},
    {name: "Great Britain", id: "olympics_GBR"},
    {name: "Grenada", id: "olympics_GRN"},
    {name: "Guam", id: "olympics_GUM"},
    {name: "Guatemala", id: "olympics_GUA"},
    {name: "Guyana", id: "olympics_GUY"},
    {name: "Guinea", id: "olympics_GUI"},
    {name: "Guinea-Bissau", id: "olympics_GBS"},
    {name: "Equatorial Guinea", id: "olympics_GEQ"},
    {name: "Haiti", id: "olympics_HAI"},
    {name: "Honduras", id: "olympics_HON"},
    {name: "Hong Kong, China", id: "olympics_HKG"},
    {name: "Hungary", id: "olympics_HUN"},
    {name: "Yemen", id: "olympics_YEM"},
    {name: "Cayman Islands", id: "olympics_CAY"},
    {name: "Cook Islands", id: "olympics_COK"},
    {name: "Marshall Islands", id: "olympics_MHL"},
    {name: "Solomon Islands", id: "olympics_SOL"},
    {name: "Virgin Islands", id: "olympics_ISV"},
    {name: "British Virgin Islands", id: "olympics_IVB"},
    {name: "India", id: "olympics_IND"},
    {name: "Indonesia", id: "olympics_INA"},
    {name: "Iraq", id: "olympics_IRQ"},
    {name: "Ireland", id: "olympics_IRL"},
    {name: "Iceland", id: "olympics_ISL"},
    {name: "Israel", id: "olympics_ISR"},
    {name: "Italy", id: "olympics_ITA"},
    {name: "Jamaica", id: "olympics_JAM"},
    {name: "Japan", id: "olympics_JPN"},
    {name: "Jordan", id: "olympics_JOR"},
    {name: "Kiribati", id: "olympics_KIR"},
    {name: "Kosovo", id: "olympics_KOS"},
    {name: "Kuwait", id: "olympics_KUW"},
    {name: "Lesotho", id: "olympics_LES"},
    {name: "Latvia", id: "olympics_LAT"},
    {name: "Lebanon", id: "olympics_LIB"},
    {name: "Liberia", id: "olympics_LBR"},
    {name: "Libya", id: "olympics_LBA"},
    {name: "Liechtenstein", id: "olympics_LIE"},
    {name: "Lithuania", id: "olympics_LTU"},
    {name: "Luxembourg", id: "olympics_LUX"},
    {name: "Madagascar", id: "olympics_MAD"},
    {name: "Malaysia", id: "olympics_MAS"},
    {name: "Malawi", id: "olympics_MAW"},
    {name: "Maldives", id: "olympics_MDV"},
    {name: "Mali", id: "olympics_MLI"},
    {name: "Malta", id: "olympics_MLT"},
    {name: "Morocco", id: "olympics_MAR"},
    {name: "Mauritius", id: "olympics_MRI"},
    {name: "Mauritania", id: "olympics_MTN"},
    {name: "Mexico", id: "olympics_MEX"},
    {name: "Mozambique", id: "olympics_MOZ"},
    {name: "Monaco", id: "olympics_MON"},
    {name: "Mongolia", id: "olympics_MGL"},
    {name: "Montenegro", id: "olympics_MNE"},
    {name: "Myanmar", id: "olympics_MYA"},
    {name: "Namibia", id: "olympics_NAM"},
    {name: "Nauru", id: "olympics_NRU"},
    {name: "Nepal", id: "olympics_NEP"},
    {name: "Nicaragua", id: "olympics_NCA"},
    {name: "Niger", id: "olympics_NIG"},
    {name: "Nigeria", id: "olympics_NGR"},
    {name: "Norway", id: "olympics_NOR"},
    {name: "New Zealand", id: "olympics_NZL"},
    {name: "Oman", id: "olympics_OMA"},
    {name: "Netherlands", id: "olympics_NED"},
    {name: "Palau", id: "olympics_PLW"},
    {name: "Palestine", id: "olympics_PLE"},
    {name: "Panama", id: "olympics_PAN"},
    {name: "Papua New Guinea", id: "olympics_PNG"},
    {name: "Pakistan", id: "olympics_PAK"},
    {name: "Paraguay", id: "olympics_PAR"},
    {name: "Peru", id: "olympics_PER"},
    {name: "Poland", id: "olympics_POL"},
    {name: "Puerto Rico", id: "olympics_PUR"},
    {name: "Portugal", id: "olympics_POR"},
    {name: "Kenya", id: "olympics_KEN"},
    {name: "Kyrgyzstan", id: "olympics_KGZ"},
    {name: "Central African Republic", id: "olympics_CAF"},
    {name: "Republic of Korea", id: "olympics_KOR"},
    {name: "Republic of Moldova", id: "olympics_MDA"},
    {name: "Democratic Republic of the Congo", id: "olympics_COD"},
    {name: "Dominican Republic", id: "olympics_DOM"},
    {name: "Islamic Republic of Iran", id: "olympics_IRI"},
    {name: "People's Republic of China", id: "olympics_CHN"},
    {name: "Democratic People's Republic of Korea", id: "olympics_PRK"},
    {name: "Lao People's Democratic Republic", id: "olympics_LAO"},
    {name: "Czech Republic", id: "olympics_CZE"},
    {name: "Romania", id: "olympics_ROU"},
    {name: "Rwanda", id: "olympics_RWA"},
    {name: "Samoa", id: "olympics_SAM"},
    {name: "American Samoa", id: "olympics_ASA"},
    {name: "San Marino", id: "olympics_SMR"},
    {name: "Saint Lucia", id: "olympics_LCA"},
    {name: "Saint Kitts and Nevis", id: "olympics_SKN"},
    {name: "São Tomé and Príncipe", id: "olympics_STP"},
    {name: "Saint Vincent and the Grenadines", id: "olympics_VIN"},
    {name: "Senegal", id: "olympics_SEN"},
    {name: "Sierra Leone", id: "olympics_SLE"},
    {name: "Serbia", id: "olympics_SRB"},
    {name: "Seychelles", id: "olympics_SEY"},
    {name: "Syria", id: "olympics_SYR"},
    {name: "Somalia", id: "olympics_SOM"},
    {name: "Sri Lanka", id: "olympics_SRI"},
    {name: "Swaziland", id: "olympics_SWZ"},
    {name: "Sudan", id: "olympics_SUD"},
    {name: "South Sudan", id: "olympics_SSD"},
    {name: "Sweden", id: "olympics_SWE"},
    {name: "Switzerland", id: "olympics_SUI"},
    {name: "Suriname", id: "olympics_SUR"},
    {name: "Thailand", id: "olympics_THA"},
    {name: "Chinese Taipei", id: "olympics_TPE"},
    {name: "Tajikistan", id: "olympics_TJK"},
    {name: "Tanzania", id: "olympics_TAN"},
    {name: "Timor-Leste", id: "olympics_TLS"},
    {name: "Togo", id: "olympics_TOG"},
    {name: "Tonga", id: "olympics_TGA"},
    {name: "Trinidad and Tobago", id: "olympics_TTO"},
    {name: "Tunisia", id: "olympics_TUN"},
    {name: "Turkmenistan", id: "olympics_TKM"},
    {name: "Turkey", id: "olympics_TUR"},
    {name: "Tuvalu", id: "olympics_TUV"},
    {name: "Ukraine", id: "olympics_UKR"},
    {name: "Uganda", id: "olympics_UGA"},
    {name: "Uruguay", id: "olympics_URU"},
    {name: "Uzbekistan", id: "olympics_UZB"},
    {name: "Vanuatu", id: "olympics_VAN"},
    {name: "Venezuela", id: "olympics_VEN"},
    {name: "Vietnam", id: "olympics_VIE"},
    {name: "Zambia", id: "olympics_ZAM"},
    {name: "Zimbabwe", id: "olympics_ZIM"},
    {name: "Refugee Olympic Athletes", id: "olympics_ROA"},
    {name: "Brazil", id: "olympics_BRA"}]